# docker compose -f infra/docker-compose.local.yml up
version: "3.8"
services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: tech_accidents_backend
    restart: always
    volumes:
      - sqllite_data:/app
    ports:
      - "8001:8001"
    env_file:
      - ../.env
volumes:
  sqllite_data:
