# docker compose -f infra/docker-compose.local.yml up
version: "3.8"
services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: tech_accidents_backend
    restart: always
    volumes:
      - ../tech_accident_db_local.db:/app/tech_accident_db_local.db
      - ../db_backups:/app/db_backups  # монтируем каталог для бэкапов БД
      - ../logs:/app/logs  # монтируем каталог для логов
#      - sqllite_data:/app  # так монтируется целиком каталог приложения (нужно удолять образ при каждом деплое)
    ports:
      - "8001:8001"
    env_file:
      - ../.env
# volumes:
#  sqllite_data:
