"""Add relashionship model TasksFiles BLOB

Revision ID: 3ad04465b2ec
Revises: 2e48d181cbda
Create Date: 2024-04-27 09:40:59.031345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad04465b2ec'
down_revision = '2e48d181cbda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file', sa.BLOB(), nullable=False))
    # op.alter_column('user', 'created_at',
    #            existing_type=sa.DATE(),
    #            type_=sa.TIMESTAMP(),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('user', 'updated_at',
    #            existing_type=sa.DATE(),
    #            type_=sa.TIMESTAMP(),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('user', 'updated_at',
    #            existing_type=sa.TIMESTAMP(),
    #            type_=sa.DATE(),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('user', 'created_at',
    #            existing_type=sa.TIMESTAMP(),
    #            type_=sa.DATE(),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('files', 'file')
    # ### end Alembic commands ###
