"""Add relashionship model SuspensionFiles

Revision ID: dbb158ca220f
Revises: 3ad04465b2ec
Create Date: 2024-06-30 14:20:34.162348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb158ca220f'
down_revision = '3ad04465b2ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suspensions_files',
    sa.Column('suspension_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    # sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['suspension_id'], ['suspensions.id'], ),
    sa.PrimaryKeyConstraint('suspension_id', 'file_id')
    )

    with op.batch_alter_table("suspensions") as batch_op:
        batch_op.alter_column('datetime_start', new_column_name='suspension_start')  # somehow it seems to be working
        batch_op.alter_column('datetime_finish', new_column_name='suspension_finish')  # somehow it seems to be working

    with op.batch_alter_table("tasks") as batch_op:
        batch_op.alter_column('executor', new_column_name='executor_id')  # somehow but it seems to be working

def downgrade() -> None:
    with op.batch_alter_table("tasks") as batch_op:
        batch_op.alter_column('executor_id', new_column_name='executor')  # somehow but it seems to be working

    with op.batch_alter_table("suspensions") as batch_op:
        batch_op.alter_column('suspension_finish', new_column_name='datetime_finish')  # somehow it seems to be working
        batch_op.alter_column('suspension_start', new_column_name='datetime_start')  # somehow it seems to be working

    op.drop_table('suspensions_files')
